### PR TITLE
WIP: Update dependencies for both Composer and NPM

### PR DESCRIPTION
**Pull request by MarcyLina**
In this PR I have updated composer.json and package.json with current versions of outdated packages. I then tested to make sure the page can still run and cleaned up error outputs. The reason I have marked this WIP is that we have 2 caveats with a couple of the packages and I was unsure how you wanted me to proceed:

- Laravel Mix breaks at the latest version, 6.0.10, so instead, I updated it to version 5.0.9
- Tailwind breaks at the latest version, 2.0.2, so instead, I updated it to 1.9.6

### CODE REVIEW

**Comment by bakerkretzmar** [comment]
@MarcyLina thanks! Same question here, what exactly breaks with those updates? 😅

**Comment by elazar** [comment]
> @MarcyLina thanks! Same question here, what exactly breaks with those updates? sweat_smile

I'm curious about this myself. I submitted #78, which is admittedly limited to upgrading NPM dependencies, but I was able to get it building successfully.

**Comment by MarcyLina** [comment]
Hello!  
For the Tailwind error, I am getting:
`In helpers.php line 104:  Unable to locate Mix file: /css/main.css. `

And the mix error is:
`error: unknown option --hide-modules`
`Exit status 2`
`Failed at the @ local script.`

The same goes for both jigsaw-docs-template and jigsaw-blog-template

**Comment by elazar** [comment]
[The `--hide-modules` flag was deprecated](https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md#update-your-npm-scripts); I had to [remove it](https://github.com/tighten/jigsaw-blog-template/pull/78/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4) as well.

I'm guessing that `Unable to locate Mix file: /css/main.css` is happening because the error related to `--hide-modules` is causing your bundle build to fail.

**Comment by bakerkretzmar** [comment]
Thanks @MarcyLina and @elazar! I'm punting on Tailwind 2 for now since it has breaking changes and we should review the look and behaviour of that upgrade more closely, but I updated to Mix 6.

**Pull request merged**
